#!/bin/bash

: ${ETCD_BIN_VERSION:=2.0.13}

case "$(uname -s)" in
  Darwin)
    ETCD_PATH=etcd-v${ETCD_BIN_VERSION}-darwin-amd64
    ETCD_FILE=${ETCD_PATH}.zip
    EXTRACT=unzip
    ;;
  Linux)
    ETCD_PATH=etcd-v${ETCD_BIN_VERSION}-linux-amd64
    ETCD_FILE=${ETCD_PATH}.tar.gz
    EXTRACT="tar -zxf"
    ;;
  *)
    echo "Unsupported operating system: `uname -s`"
    exit 1
    ;;
esac

mkdir .bin
pushd .bin
wget https://github.com/coreos/etcd/releases/download/v${ETCD_BIN_VERSION}/${ETCD_FILE} -O ${ETCD_FILE}
${EXTRACT} ${ETCD_FILE}
mv ${ETCD_PATH}/etcd .
popd
